### ISSUE TITLE
is_valid() shortcut raises InvalidMpanError when a short MPAN is passed in

### ISSUE THREAD

**Issue by limedaniel** [limejump/mpan#3]
```
>>> import mpan
>>> mpan.is_valid('[an MPAN missing the last digit]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/mpan.py", line 426, in is_valid
    return MPAN(raw_string).is_valid
  File "/usr/local/lib/python3.8/site-packages/mpan.py", line 360, in __init__
    raise InvalidMPANError("This doesn't look like an MPAN")
mpan.InvalidMPANError: This doesn't look like an MPAN
```

`is_valid()` passes the string to the MPAN class but doesn't handle cases where `__init__()` rejects the string as clearly not an MPAN.  It should catch this exception and return `False`.

**Comment by limedaniel** [comment]
Fixed in 1.0.3
